### ISSUE TITLE
Bug when displaying notifications on Login screen

### ISSUE THREAD

**Issue by Samuel-Risner** [MaximilianHausen/better-mebis#1]
The notification text is barely visible since it almost shares the same colour with the background. The text should be white or smth.

![grafik](https://user-images.githubusercontent.com/96385448/197571136-2b38db75-41b7-4b9b-8993-ca3874b4e595.png)

**Comment by moritzlerch** [comment]
Iiiieh, @MaximilianHausen fix please 🐛🐛

**Comment by MaximilianHausen** [comment]
Fixed in 434cc0054b3cee5b6f9f2682be3ddbcef3b85591
